GET http://localhost:3007/users/
###
POST http://localhost:3007/register
Content-Type: application/json

{
  "full_name": "test one",
  "email": "test@one.com",
  "password": "test1"
}
###
POST http://localhost:3007/login
Content-Type: application/json

{
  "email": "test@one.com",
  "password": "test1"
}
###