###==================================users
GET http://localhost:3007/users/
###
POST http://localhost:3007/register
Content-Type: application/json

{
  "full_name": "test one",
  "email": "test@one.com",
  "password": "test1"
}
###
POST http://localhost:3007/login
Content-Type: application/json

{
  "email": "test@one.com",
  "password": "test1"
}
###==================================accounts
GET http://localhost:3007/accounts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE5LCJpYXQiOjE2NTM2MzI1MTEsImV4cCI6MTY1MzYzNjExMX0.UQtftszlYSI7VZmYr-KpCcJnnXx1LCpJ35c7jCewKcM
###
POST http://localhost:3007/accounts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE5LCJpYXQiOjE2NTM2MzI1MTEsImV4cCI6MTY1MzYzNjExMX0.UQtftszlYSI7VZmYr-KpCcJnnXx1LCpJ35c7jCewKcM

{
  "group_id": 3
 }
###